image: alpine

#compile:
#  stage: build
#  script:
#  - make src
#  only:
#  - master

pages:
  stage: deploy
  script:
  - apk update && apk add doxygen && apk graphviz
  - doxygen doxygen/Doxyfile
  - mv doxygen/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master