image: alpine

build_searchfolder:
  stage: build
  script:
  - apk update && apk add make bash build-base gcc
  - make src
  only:
  - master

unit_tests:
  stage: test
  script:
  - apk update && apk add make bash build-base gcc
  - make tests
  only:
  - master

pages:
  stage: deploy
  script:
  - apk update && apk add doxygen graphviz font-adobe-100dpi
  - cd doxygen
  - mkdir html
  - doxygen Doxyfile > html/log.txt
  - cd ..
  - mv doxygen/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master