image: alpine

buil_searchfolder:
  stage: build
  script:
  - make src
  only:
  - master

unit_tests:
  stage: test
  script:
  - make tests
  only:
  - master

pages:
  stage: deploy
  script:
  - apk update && apk add doxygen && apk add graphviz
  - cd doxygen 
  - doxygen Doxyfile
  - cd ..
  - mv doxygen/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master